INSERT OR IGNORE INTO search_terms (term) VALUES ('software engineer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('developer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('designer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('product manager');
INSERT OR IGNORE INTO search_terms (term) VALUES ('data scientist');
INSERT OR IGNORE INTO search_terms (term) VALUES ('devops engineer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('frontend developer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('backend developer');
INSERT OR IGNORE INTO search_terms (term) VALUES ('fullstack developer');

INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('at', 'Austria', '奥地利', 'austria', 'Europe/Vienna');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('au', 'Australia', '澳大利亚', 'australia', 'Australia/Sydney');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('be', 'Belgium', '比利时', 'belgium', 'Europe/Brussels');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('ca', 'Canada', '加拿大', 'canada', 'America/Toronto');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('ch', 'Switzerland', '瑞士', 'switzerland', 'Europe/Zurich');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('de', 'Germany', '德国', 'germany', 'Europe/Berlin');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('dk', 'Denmark', '丹麦', 'denmark', 'Europe/Copenhagen');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('fi', 'Finland', '芬兰', 'finland', 'Europe/Helsinki');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('fr', 'France', '法国', 'france', 'Europe/Paris');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('gb', 'United Kingdom', '英国', 'united-kingdom', 'Europe/London');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('ie', 'Ireland', '爱尔兰', 'ireland', 'Europe/Dublin');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('il', 'Israel', '以色列', 'israel', 'Asia/Jerusalem');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('jp', 'Japan', '日本', 'japan', 'Asia/Tokyo');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('nl', 'Netherlands', '荷兰', 'netherlands', 'Europe/Amsterdam');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('no', 'Norway', '挪威', 'norway', 'Europe/Oslo');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('nz', 'New Zealand', '新西兰', 'new-zealand', 'Pacific/Auckland');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('se', 'Sweden', '瑞典', 'sweden', 'Europe/Stockholm');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('sg', 'Singapore', '新加坡', 'singapore', 'Asia/Singapore');
INSERT OR IGNORE INTO countries (code, name, name_cn, slug, timezone) VALUES ('us', 'United States', '美国', 'united-states', 'America/New_York');
