name = "yuanchengdao"
main = "src/index.ts"
compatibility_date = "2024-12-01"
account_id = "9a429384e601502567594df3cd611836"
workers_dev = false

[vars]
SITE_URL = "https://yuanchengdao.com"
STATIC_URL = "https://static.yuanchengdao.com"
GA_ID = "G-MZGV7SFZ9F"

[[d1_databases]]
binding = "DB"
database_name = "yuanchengdao"
database_id = "4950fa7a-ca80-4948-9ec9-7eda9592ea44"

[[r2_buckets]]
binding = "R2"
bucket_name = "yuanchengdao"

# Cron trigger: runs every minute, processes 1 search query per run
[triggers]
crons = ["*/3 * * * *"]
