-- Second pass over production: every source that turned out to be a reposter.
-- Derived from the real via distribution (1,619 values) and apply-link host
-- distribution (753 hosts) in jobs_crawled, not from guesswork.
--
-- The bulk of the farm runs on free web hosting, so the provider domains are
-- blocked directly: that covers the sites already seen and the next batch too.
INSERT OR IGNORE INTO blocked_sources (pattern, match_type, note, is_active) VALUES
  ('hiringremotejobs.net', 'domain', '采集/搬运站', 1),
  ('talentify.io', 'domain', '采集/搬运站（via 规则已拦，补齐域名）', 1),
  ('career.com', 'domain', '采集/搬运站（via 规则已拦，补齐域名）', 1),
  ('liveblog365.com', 'domain', '免费主机，承载 37 个采集子站', 1),
  ('up.railway.app', 'domain', 'Railway 默认子域，观察到的 11 个全是采集站（不影响 Railway 自有域名）', 1),
  ('wuaze.com', 'domain', 'InfinityFree 免费主机', 1),
  ('unaux.com', 'domain', 'InfinityFree 免费主机', 1),
  ('infinityfree.me', 'domain', 'InfinityFree 免费主机', 1),
  ('infinityfreeapp.com', 'domain', 'InfinityFree 免费主机', 1),
  ('infinityfree.io', 'domain', 'InfinityFree 免费主机', 1),
  ('42web.io', 'domain', 'InfinityFree 免费主机', 1),
  ('kesug.com', 'domain', 'InfinityFree 免费主机', 1),
  ('byethost7.com', 'domain', 'Byet 免费主机', 1),
  ('hstn.me', 'domain', 'InfinityFree 免费主机', 1),
  ('zya.me', 'domain', 'InfinityFree 免费主机', 1),
  ('10001mb.com', 'domain', '免费主机', 1),
  ('epizy.com', 'domain', 'InfinityFree 免费主机', 1),
  ('lovestoblog.com', 'domain', '免费主机', 1),
  ('page.gd', 'domain', '免费主机', 1),
  ('html-5.me', 'domain', '免费子域', 1),
  ('2kool4u.net', 'domain', '免费子域', 1),
  ('is-great.net', 'domain', '免费子域', 1),
  ('web1337.net', 'domain', '免费子域', 1),
  ('social-networking.me', 'domain', '免费子域', 1),
  ('fast-page.org', 'domain', '免费子域', 1),
  ('my-board.org', 'domain', '免费子域', 1),
  ('dedyn.io', 'domain', 'deSEC 免费动态 DNS', 1),
  ('remotecrust.vercel.app', 'domain', '采集站（只封此子域，不封 vercel.app）', 1),
  ('main.d3mhslpmrpo4el.amplifyapp.com', 'domain', '采集站（只封此子域，不封 amplifyapp.com）', 1),
  ('topsiksha.com', 'domain', '被挂采集页', 1),
  ('superconceptclasses.in', 'domain', '被挂采集页', 1),
  ('searchestate.space', 'domain', '采集站', 1),
  ('winzons.com', 'domain', '采集站', 1),
  ('bebee.com', 'domain', '采集/搬运站', 1),
  ('tealhq.com', 'domain', '采集/搬运站', 1),
  ('jobilize.com', 'domain', '采集/搬运站', 1),
  ('mysmartpros.com', 'domain', '采集/搬运站', 1),
  ('recruit.net', 'domain', '采集/搬运站', 1),
  ('jobright.ai', 'domain', '采集/搬运站', 1),
  ('theladders.com', 'domain', '采集/搬运站', 1),
  ('careervault.io', 'domain', '采集/搬运站', 1),
  ('career.io', 'domain', '采集/搬运站', 1),
  ('jobmesh.io', 'domain', '采集/搬运站', 1),
  ('jobmesh.co.uk', 'domain', '采集/搬运站', 1),
  ('lifeworq.com', 'domain', '采集/搬运站', 1),
  ('up2staff.com', 'domain', '采集/搬运站', 1),
  ('remote.co', 'domain', '采集/搬运站', 1),
  ('remoteleaf.com', 'domain', '采集/搬运站', 1),
  ('haystackapp.io', 'domain', '采集/搬运站', 1),
  ('tsenta.com', 'domain', '采集/搬运站', 1),
  ('jobzmall.com', 'domain', '采集/搬运站', 1),
  ('mediabistro.com', 'domain', '采集/搬运站', 1),
  ('jaabz.com', 'domain', '采集/搬运站', 1),
  ('remotejobs.org', 'domain', '采集/搬运站', 1),
  ('remotefront.com', 'domain', '采集/搬运站', 1),
  ('sorce.jobs', 'domain', '采集/搬运站', 1),
  ('bandana.com', 'domain', '采集/搬运站', 1),
  ('tallo.com', 'domain', '采集/搬运站', 1),
  ('virtualvocations.com', 'domain', '采集/搬运站', 1),
  ('sonara.ai', 'domain', '采集/搬运站', 1),
  ('simplify.jobs', 'domain', '采集/搬运站', 1),
  ('startup.jobs', 'domain', '采集/搬运站', 1),
  ('trabajo.org', 'domain', '采集/搬运站', 1),
  ('expertini.com', 'domain', '采集/搬运站', 1),
  ('thebigjobsite.com', 'domain', '采集/搬运站', 1),
  ('talents.vaia.com', 'domain', '采集/搬运站', 1),
  ('talents.studysmarter.co.uk', 'domain', '采集/搬运站', 1),
  ('talents.studysmarter.de', 'domain', '采集/搬运站', 1),
  ('swooped.co', 'domain', '采集/搬运站', 1),
  ('grabjobs.co', 'domain', '采集/搬运站', 1),
  ('pitchmeai.com', 'domain', '采集/搬运站', 1),
  ('sidehustles.com', 'domain', '采集/搬运站', 1),
  ('kitjob.in', 'domain', '采集/搬运站', 1),
  ('earnbetter.com', 'domain', '采集/搬运站', 1),
  ('hiring.cafe', 'domain', '采集/搬运站', 1),
  ('jobaaj.com', 'domain', '采集/搬运站', 1),
  ('remotescout24.com', 'domain', '采集/搬运站', 1),
  ('experteer.com', 'domain', '采集/搬运站', 1),
  ('strivetasks.com', 'domain', '采集/搬运站', 1),
  ('theelitejob.com', 'domain', '采集/搬运站', 1),
  ('applyall.com', 'domain', '采集/搬运站', 1),
  ('salutemyjob.com', 'domain', '采集/搬运站', 1),
  ('opentalent.in', 'domain', '采集/搬运站', 1),
  ('applyblast.com', 'domain', '采集/搬运站', 1),
  ('wfhbridge.com', 'domain', '采集/搬运站', 1),
  ('cosmoquick.com', 'domain', '采集/搬运站', 1),
  ('remotepositionshirings.com', 'domain', '采集/搬运站', 1),
  ('remote4africa.com', 'domain', '采集/搬运站', 1),
  ('iitjobs.com', 'domain', '采集/搬运站', 1),
  ('euremotejobs.com', 'domain', '采集/搬运站', 1),
  ('employbl.com', 'domain', '采集/搬运站', 1),
  ('sonicjobs.com', 'domain', '采集/搬运站', 1),
  ('jobera.com', 'domain', '采集/搬运站', 1),
  ('nogigiddy.com', 'domain', '采集/搬运站', 1),
  ('echojobs.io', 'domain', '采集/搬运站', 1),
  ('remotesource.com', 'domain', '采集/搬运站', 1),
  ('aidoos.com', 'domain', '采集/搬运站', 1),
  ('pbridgeco.com', 'domain', '采集/搬运站', 1),
  ('nextraise.ai', 'domain', '采集/搬运站', 1),
  ('gorodeo.app', 'domain', '采集/搬运站', 1),
  ('mindpal.co', 'domain', '采集/搬运站', 1),
  ('diversityjobs.com', 'domain', '采集/搬运站', 1),
  ('yulys.com', 'domain', '采集/搬运站', 1),
  ('remotejobsfinder.co', 'domain', '采集/搬运站', 1),
  ('todays-jobs.com', 'domain', '采集/搬运站', 1),
  ('remotestack.in', 'domain', '采集/搬运站', 1),
  ('naukrimitra.in', 'domain', '采集/搬运站', 1),
  ('swiftcruit.ai', 'domain', '采集/搬运站', 1),
  ('careerprogrid.com', 'domain', '采集/搬运站', 1),
  ('talanto.work', 'domain', '采集/搬运站', 1),
  ('useparallel.com', 'domain', '采集/搬运站', 1),
  ('novexwork.net', 'domain', '采集/搬运站', 1),
  ('hirify.me', 'domain', '采集/搬运站', 1),
  ('jobless.dev', 'domain', '采集/搬运站', 1),
  ('findmyremote.ai', 'domain', '采集/搬运站', 1),
  ('remotivated.com', 'domain', '采集/搬运站', 1),
  ('notify.careers', 'domain', '采集/搬运站', 1),
  ('jobtrees.com', 'domain', '采集/搬运站', 1),
  ('optimhire.com', 'domain', '采集/搬运站', 1),
  ('resumekart.com', 'domain', '采集/搬运站', 1),
  ('opentoworkremote.com', 'domain', '采集/搬运站', 1),
  ('karkidi.com', 'domain', '采集/搬运站', 1),
  ('ai-search.io', 'domain', '采集/搬运站', 1),
  ('goremotejob.com', 'domain', '采集/搬运站', 1),
  ('sovexpath.com', 'domain', '采集/搬运站', 1),
  ('truemote.com', 'domain', '采集/搬运站', 1),
  ('torre.ai', 'domain', '采集/搬运站', 1),
  ('nexxt.com', 'domain', '采集/搬运站', 1),
  ('mylivecv.com', 'domain', '采集/搬运站', 1),
  ('lazyapply.com', 'domain', '采集/搬运站', 1),
  ('hirethebetter.com', 'domain', '采集/搬运站', 1),
  ('aijobs.com', 'domain', '采集/搬运站', 1),
  ('workremotespot.com', 'domain', '采集/搬运站', 1),
  ('unityhirefind.com', 'domain', '采集/搬运站', 1),
  ('empllo.com', 'domain', '采集/搬运站', 1),
  ('meetfrank.com', 'domain', '采集/搬运站', 1),
  ('careercircle.com', 'domain', '采集/搬运站', 1),
  ('jobijoba.co.uk', 'domain', '采集/搬运站', 1),
  ('adzuna.co.uk', 'domain', '采集/搬运站', 1),
  ('adzuna.in', 'domain', '采集/搬运站', 1),
  ('bebee', 'via', '采集/搬运站', 1),
  ('flexboard', 'via', '采集/搬运站', 1),
  ('flexionis', 'via', '采集/搬运站', 1),
  ('teal', 'via', '采集/搬运站', 1),
  ('jobright', 'via', '采集/搬运站', 1),
  ('ladders', 'via', '采集/搬运站', 1),
  ('up2staff', 'via', '采集/搬运站', 1),
  ('recruit.net', 'via', '采集/搬运站', 1),
  ('career vault', 'via', '采集/搬运站', 1),
  ('career.io', 'via', '采集/搬运站', 1),
  ('jobmesh', 'via', '采集/搬运站', 1),
  ('hiredock', 'via', '采集/搬运站', 1),
  ('jobhub', 'via', '采集/搬运站', 1),
  ('remote4africa', 'via', '采集/搬运站', 1),
  ('the elite job', 'via', '采集/搬运站', 1),
  ('the elitejob', 'via', '采集/搬运站', 1),
  ('virtual vocations', 'via', '采集/搬运站', 1),
  ('grabjobs', 'via', '采集/搬运站', 1),
  ('trabajo.org', 'via', '采集/搬运站', 1),
  ('remoteleaf', 'via', '采集/搬运站', 1),
  ('haystack', 'via', '采集/搬运站', 1),
  ('applyall', 'via', '采集/搬运站', 1),
  ('jaabz', 'via', '采集/搬运站', 1),
  ('remotefront', 'via', '采集/搬运站', 1),
  ('remotejobs.org', 'via', '采集/搬运站', 1),
  ('remotehub', 'via', '采集/搬运站', 1),
  ('mediabistro', 'via', '采集/搬运站', 1),
  ('media bistro', 'via', '采集/搬运站', 1),
  ('jobzmall', 'via', '采集/搬运站', 1),
  ('tallo', 'via', '采集/搬运站', 1),
  ('simplify', 'via', '采集/搬运站', 1),
  ('torre.ai', 'via', '采集/搬运站', 1),
  ('jobilize', 'via', '采集/搬运站', 1),
  ('jobtrees', 'via', '采集/搬运站', 1),
  ('sonicjobs', 'via', '采集/搬运站', 1),
  ('career.com', 'via', '采集/搬运站', 1),
  ('earnbetter', 'via', '采集/搬运站', 1),
  ('bandana.com', 'via', '采集/搬运站', 1),
  ('mysmartpros', 'via', '采集/搬运站', 1),
  ('cosmoquick', 'via', '采集/搬运站', 1),
  ('mindpal', 'via', '采集/搬运站', 1),
  ('jobera', 'via', '采集/搬运站', 1),
  ('aidoos', 'via', '采集/搬运站', 1),
  ('startup jobs', 'via', '采集/搬运站', 1),
  ('remote.co', 'via', '采集/搬运站', 1),
  ('jobrapido.com', 'via', '采集/搬运站', 1),
  ('himalayas.app', 'via', '采集/搬运站', 1),
  ('nexxt', 'via', '采集/搬运站', 1),
  ('lifeworq', 'via', '采集/搬运站', 1),
  ('swooped', 'via', '采集/搬运站', 1),
  ('hiring cafe', 'via', '采集/搬运站', 1),
  ('echojobs', 'via', '采集/搬运站', 1),
  ('sonara', 'via', '采集/搬运站', 1),
  ('ai search', 'via', '采集/搬运站', 1),
  ('remotescout24', 'via', '采集/搬运站', 1),
  ('virtualvocations', 'via', '采集/搬运站', 1),
  ('careersprint', 'via', '采集/搬运站', 1),
  ('jobflarely', 'via', '采集/搬运站', 1),
  ('remote zest jobs', 'via', '采集/搬运站', 1),
  ('remote click jobs', 'via', '采集/搬运站', 1),
  ('remote quest jobs', 'via', '采集/搬运站', 1),
  ('remote target jobs', 'via', '采集/搬运站', 1),
  ('remote spark', 'via', '采集/搬运站', 1),
  ('remote nova', 'via', '采集/搬运站', 1),
  ('vacancy global pro', 'via', '采集/搬运站', 1),
  ('vacancy target jobs', 'via', '采集/搬运站', 1),
  ('halvolink', 'via', '采集/搬运站', 1),
  ('careersync', 'via', '采集/搬运站', 1),
  ('anchormust', 'via', '采集/搬运站', 1),
  ('anchorpoint', 'via', '采集/搬运站', 1),
  ('novaedge', 'via', '采集/搬运站', 1),
  ('taskium', 'via', '采集/搬运站', 1),
  ('taskfusion', 'via', '采集/搬运站', 1),
  ('quickswoop', 'via', '采集/搬运站', 1),
  ('workfinity', 'via', '采集/搬运站', 1),
  ('rosterly', 'via', '采集/搬运站', 1),
  ('flexlith', 'via', '采集/搬运站', 1),
  ('alignlist', 'via', '采集/搬运站', 1),
  ('sorce', 'via', '采集/搬运站', 1),
  ('zipzap', 'via', '采集/搬运站', 1),
  ('wfhforgeon', 'via', '采集/搬运站', 1),
  ('miragely', 'via', '采集/搬运站', 1),
  ('willowyn', 'via', '采集/搬运站', 1),
  ('hirnova', 'via', '采集/搬运站', 1),
  ('hirequorum', 'via', '采集/搬运站', 1),
  ('hirequill', 'via', '采集/搬运站', 1),
  ('hirevector', 'via', '采集/搬运站', 1),
  ('hirebase', 'via', '采集/搬运站', 1),
  ('hirevault', 'via', '采集/搬运站', 1),
  ('hirestream', 'via', '采集/搬运站', 1),
  ('hirerivet', 'via', '采集/搬运站', 1),
  ('hireclip', 'via', '采集/搬运站', 1),
  ('jobspawn', 'via', '采集/搬运站', 1),
  ('jobease', 'via', '采集/搬运站', 1),
  ('jobedge', 'via', '采集/搬运站', 1),
  ('jobstream', 'via', '采集/搬运站', 1),
  ('jobrise', 'via', '采集/搬运站', 1),
  ('jobluent', 'via', '采集/搬运站', 1),
  ('remotivix', 'via', '采集/搬运站', 1),
  ('remotica', 'via', '采集/搬运站', 1),
  ('remoteai', 'via', '采集/搬运站', 1),
  ('talents by vaia', 'via', '采集/搬运站', 1),
  ('talents by studysmarter', 'via', '采集/搬运站', 1),
  ('naukri mitra', 'via', '采集/搬运站', 1),
  ('jobs4wfh', 'via', '采集/搬运站', 1),
  ('us-wfhub', 'via', '采集/搬运站', 1),
  ('wfh', 'via', '采集/搬运站', 1),
  ('careerprogrid', 'via', '采集/搬运站', 1),
  ('career.zycto', 'via', '采集/搬运站', 1),
  ('iitjobs', 'via', '采集/搬运站', 1),
  ('eu remote jobs', 'via', '采集/搬运站', 1),
  ('remote jobs usa', 'via', '采集/搬运站', 1),
  ('remote jobs finder', 'via', '采集/搬运站', 1),
  ('24-mag', 'via', '采集/搬运站', 1),
  ('hivlance', 'via', '采集/搬运站', 1),
  ('pbridge', 'via', '采集/搬运站', 1),
  ('jobflow', 'via', '采集/搬运站', 1),
  ('remoteforge', 'via', '采集/搬运站', 1),
  ('hirevelo', 'via', '采集/搬运站', 1),
  ('remotepulse', 'via', '采集/搬运站', 1),
  ('remotejobs', 'via', '采集/搬运站', 1);

-- Production volume shows these seeded-but-disabled sources are pure reposters.
UPDATE blocked_sources SET is_active = 1 WHERE is_active = 0 AND pattern IN (
  'jobgether',
  'dailyremote',
  'remoterocketship',
  'remotive',
  'himalayas',
  'workingnomads',
  'justremote',
  'europeremotely',
  'flexjobs',
  'nodesk',
  'jobgether.com',
  'dailyremote.com',
  'remoterocketship.com',
  'remotive.com',
  'himalayas.app',
  'workingnomads.com',
  'justremote.co',
  'europeremotely.com',
  'flexjobs.com',
  'nodesk.co'
);
